### ISSUE TITLE
implicit declaration of function ‘zMShape3DScanFile’

### ISSUE THREAD

**Issue by n-wakisaka** [zhidao/roki#3]
The latest Zeo does not have zMShape3DScanFile.
Was zMShape3DScanFile renamed zMShape3DReadZTK?

[build log]
...
rk_chain.c: In function ‘rkChainMShape3DScanFile’:
rk_chain.c:741:8: warning: implicit declaration of function ‘zMShape3DScanFile’ [-Wimplicit-function-declaration]
   if( !zMShape3DScanFile( ms, filename ) ){
...

**Comment by n-wakisaka** [comment]
[build log]
z3d2zkc.c: In function ‘main’:
z3d2zkc.c:36:8: warning: implicit declaration of function ‘zMShape3DScanFile’; did you mean ‘zMShape3DPrintFile’? [-Wimplicit-function-declaration]
   if( !zMShape3DScanFile( &ms, argv[1] ) )

**Comment by zhidao** [comment]
Thanks for the report. I've pushed the master revision which is consistent with the update of Zeo.
