### ISSUE TITLE
division into cases in _rkLinkABIUpdateForward

### ISSUE THREAD

**Issue by n-wakisaka** [zhidao/roki#4]
The following division into cases in _rkLinkABIUpdateForward may be simplified.
https://github.com/zhidao/roki/blob/7bfd2c5722a94c89f4cbbc260c488d2dda33f924/src/rk_abi.c#L192-L199

The variable att may equal to _att in JointPrp.

_att is updated at rkLinkUpdateFrame that is called by rkChainUpdateFK.
The source cord is expanded as follows, for example with float joint.
https://github.com/zhidao/roki/blob/7bfd2c5722a94c89f4cbbc260c488d2dda33f924/src/rk_link.c#L114-L116
https://github.com/zhidao/roki/blob/7bfd2c5722a94c89f4cbbc260c488d2dda33f924/src/rk_joint_float.c#L96-L102
So the att in _rkLinkABIUpdateForward equals to _rkc(prp)->_att.

**Comment by zhidao** [comment]
Have you checked if the result wouldn't change by the replacement?

**Comment by zhidao** [comment]
Done (in a better way).
